<p>
MySocialArea.com: Password Reset</p>
<br />
<p>
INSTRUCTIONS:<br />
You have recently indicated to us that you cannot remember your password.<br />
Please go to the following link and enter the token password provided below where required.<br />
If you think you received this email in error it is possible that someone may have accidentally entered your email address 
in our password recovery page.
<br /><br />
LINK: <a href="http://mysocialarea.com/user/resetpassword">http://mysocialarea.com/user/resetpassword</a><br />
TOKEN PASSWORD: <?php echo $this->token; ?>
</p>
</div>
