<a href="/mlse/index" class="menu-item">MLSE SUCKS HOME</a><a href="/mlse/letemhaveit" class="menu-item">Let &apos;em Have it</a><a href="/mlse/feedback" class="menu-item">Feedback</a>
<div id="view-content">
	<p>
    MLSE currenty owns three major league professional sports teams which are Toronto FC, Toronto Raptors, and last AND least...the Toronto Maple Leafs. 
    None of these teams have won anything of signicance since 1967. To me, this would suggest that the problem does not lie with the players of these teams 
    but more with the management of the MLSE which borders on criminal. MLSE 
    </p>
</div>
<script type="text/javascript">
function getFacebook()
{
	$("#vw-ajax-content-1").load( "/ajaxmlseletemhaveit1/val/fb");
}

function getTwitter()
{
	$("#vw-ajax-content-1").load( "/ajaxmlseletemhaveit1/val/twtr");
}
</script>
<table>
<tr align="center">
<td>1967–68</td>
<td>74</td>
<td>33</td>
<td>31</td>
<td>10</td>
<td>--</td>
<td>76</td>
<td>209</td>
<td>176</td>
<td>634</td>
<td>5th in East</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1968–69</td>
<td>76</td>
<td>35</td>
<td>26</td>
<td>15</td>
<td>--</td>
<td>85</td>
<td>234</td>
<td>217</td>
<td>961</td>
<td>4th in East</td>
<td align="left">Lost in Quarterfinals</td>
</tr>
<tr align="center">
<td>1969–70</td>
<td>76</td>
<td>29</td>
<td>34</td>
<td>13</td>
<td>--</td>
<td>71</td>
<td>222</td>
<td>242</td>
<td>898</td>
<td>6th in East</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1970–71</td>
<td>78</td>
<td>37</td>
<td>33</td>
<td>8</td>
<td>--</td>
<td>82</td>
<td>248</td>
<td>211</td>
<td>1133</td>
<td>4th in East</td>
<td align="left">Lost in Quarterfinals</td>
</tr>
<tr align="center">
<td>1971–72</td>
<td>78</td>
<td>33</td>
<td>31</td>
<td>14</td>
<td>--</td>
<td>80</td>
<td>209</td>
<td>208</td>
<td>887</td>
<td>4th in East</td>
<td align="left">Lost in Quarterfinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1972–73</td>
<td>78</td>
<td>27</td>
<td>41</td>
<td>10</td>
<td>--</td>
<td>64</td>
<td>247</td>
<td>279</td>
<td>716</td>
<td>6th in East</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center">
<td>1973–74</td>
<td>78</td>
<td>35</td>
<td>27</td>
<td>16</td>
<td>--</td>
<td>86</td>
<td>274</td>
<td>230</td>
<td>903</td>
<td>4th in East</td>
<td align="left">Lost in Quarterfinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1974–75</td>
<td>80</td>
<td>31</td>
<td>33</td>
<td>16</td>
<td>--</td>
<td>78</td>
<td>280</td>
<td>309</td>
<td>1079</td>
<td>3rd in Adams</td>
<td align="left">Lost in Quarterfinals</td>
</tr>
<tr align="center">
<td>1975–76</td>
<td>80</td>
<td>34</td>
<td>31</td>
<td>15</td>
<td>--</td>
<td>83</td>
<td>294</td>
<td>276</td>
<td>1368</td>
<td>3rd in Adams</td>
<td align="left">Lost in Quarterfinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1976–77</td>
<td>80</td>
<td>33</td>
<td>32</td>
<td>15</td>
<td>--</td>
<td>81</td>
<td>301</td>
<td>285</td>
<td>1200</td>
<td>3rd in Adams</td>
<td align="left">Lost in Quarterfinals</td>
</tr>
<tr align="center">
<td>1977–78</td>
<td>80</td>
<td>41</td>
<td>29</td>
<td>10</td>
<td>--</td>
<td>92</td>
<td>271</td>
<td>237</td>
<td>1258</td>
<td>3rd in Adams</td>
<td align="left">Lost in Semifinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1978–79</td>
<td>80</td>
<td>34</td>
<td>33</td>
<td>13</td>
<td>--</td>
<td>81</td>
<td>267</td>
<td>252</td>
<td>1440</td>
<td>3rd in Adams</td>
<td align="left">Lost in Quarterfinals</td>
</tr>
<tr align="center">
<td>1979–80</td>
<td>80</td>
<td>35</td>
<td>40</td>
<td>5</td>
<td>--</td>
<td>75</td>
<td>304</td>
<td>327</td>
<td>1158</td>
<td>4th in Adams</td>
<td align="left">Lost in Preliminary Round</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1980–81</td>
<td>80</td>
<td>28</td>
<td>37</td>
<td>15</td>
<td>--</td>
<td>71</td>
<td>322</td>
<td>367</td>
<td>1830</td>
<td>5th in Adams</td>
<td align="left">Lost in Preliminary Round</td>
</tr>
<tr align="center">
<td>1981–82</td>
<td>80</td>
<td>20</td>
<td>44</td>
<td>16</td>
<td>--</td>
<td>56</td>
<td>298</td>
<td>380</td>
<td>1888</td>
<td>5th in Norris</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1982–83</td>
<td>80</td>
<td>28</td>
<td>40</td>
<td>12</td>
<td>--</td>
<td>68</td>
<td>293</td>
<td>330</td>
<td>1481</td>
<td>3rd in Norris</td>
<td align="left">Lost in Division Semifinals</td>
</tr>
<tr align="center">
<td>1983–84</td>
<td>80</td>
<td>26</td>
<td>45</td>
<td>9</td>
<td>--</td>
<td>61</td>
<td>303</td>
<td>387</td>
<td>1682</td>
<td>5th in Norris</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1984–85</td>
<td>80</td>
<td>20</td>
<td>52</td>
<td>8</td>
<td>--</td>
<td>48</td>
<td>253</td>
<td>358</td>
<td>1627</td>
<td>5th in Norris</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center">
<td>1985–86</td>
<td>80</td>
<td>25</td>
<td>48</td>
<td>7</td>
<td>--</td>
<td>57</td>
<td>311</td>
<td>386</td>
<td>1716</td>
<td>4th in Norris</td>
<td align="left">Lost in Division Finals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1986–87</td>
<td>80</td>
<td>32</td>
<td>42</td>
<td>6</td>
<td>--</td>
<td>70</td>
<td>286</td>
<td>319</td>
<td>1827</td>
<td>4th in Norris</td>
<td align="left">Lost in Division Finals</td>
</tr>
<tr align="center">
<td>1987–88</td>
<td>80</td>
<td>21</td>
<td>49</td>
<td>10</td>
<td>--</td>
<td>52</td>
<td>273</td>
<td>345</td>
<td>1782</td>
<td>4th in Norris</td>
<td align="left">Lost in Division Semifinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1988–89</td>
<td>80</td>
<td>28</td>
<td>46</td>
<td>6</td>
<td>--</td>
<td>62</td>
<td>259</td>
<td>342</td>
<td>1740</td>
<td>5th in Norris</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center">
<td>1989–90</td>
<td>80</td>
<td>38</td>
<td>38</td>
<td>4</td>
<td>--</td>
<td>80</td>
<td>337</td>
<td>358</td>
<td>2419</td>
<td>3rd in Norris</td>
<td align="left">Lost in Division Semifinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1990–91</td>
<td>80</td>
<td>23</td>
<td>46</td>
<td>11</td>
<td>--</td>
<td>57</td>
<td>241</td>
<td>318</td>
<td>1962</td>
<td>5th in Norris</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center">
<td>1991–92</td>
<td>80</td>
<td>30</td>
<td>43</td>
<td>7</td>
<td>--</td>
<td>67</td>
<td>234</td>
<td>294</td>
<td>1734</td>
<td>5th in Norris</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1992–93</td>
<td>84</td>
<td>44</td>
<td>29</td>
<td>11</td>
<td>--</td>
<td>99</td>
<td>288</td>
<td>241</td>
<td>1815</td>
<td>3rd in Norris</td>
<td align="left">Lost in Conference Finals</td>
</tr>
<tr align="center">
<td>1993–94</td>
<td>84</td>
<td>43</td>
<td>29</td>
<td>12</td>
<td>--</td>
<td>98</td>
<td>280</td>
<td>243</td>
<td>1877</td>
<td>2nd in Central</td>
<td align="left">Lost in Conference Finals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1994–95</td>
<td>48</td>
<td>21</td>
<td>19</td>
<td>8</td>
<td>--</td>
<td>50</td>
<td>135</td>
<td>146</td>
<td>744</td>
<td>4th in Central</td>
<td align="left">Lost in Conference Quarterfinals</td>
</tr>
<tr align="center">
<td>1995–96</td>
<td>82</td>
<td>34</td>
<td>36</td>
<td>12</td>
<td>--</td>
<td>80</td>
<td>247</td>
<td>252</td>
<td>1742</td>
<td>3rd in Central</td>
<td align="left">Lost in Conference Quarterfinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1996–97</td>
<td>82</td>
<td>30</td>
<td>44</td>
<td>8</td>
<td>--</td>
<td>68</td>
<td>230</td>
<td>273</td>
<td>1331</td>
<td>6th in Central</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center">
<td>1997–98</td>
<td>82</td>
<td>30</td>
<td>43</td>
<td>9</td>
<td>--</td>
<td>69</td>
<td>194</td>
<td>237</td>
<td>1481</td>
<td>6th in Central</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>1998–99</td>
<td>82</td>
<td>45</td>
<td>30</td>
<td>7</td>
<td>--</td>
<td>97</td>
<td>268</td>
<td>231</td>
<td>1095</td>
<td>2nd in Northeast</td>
<td align="left">Lost in Conference Finals</td>
</tr>
<tr align="center">
<td>1999–2000</td>
<td>82</td>
<td>45</td>
<td>27</td>
<td>7</td>
<td>3</td>
<td>100</td>
<td>246</td>
<td>222</td>
<td>1103</td>
<td>1st in Northeast</td>
<td align="left">Lost in Conference Semifinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>2000–01</td>
<td>82</td>
<td>37</td>
<td>29</td>
<td>11</td>
<td>5</td>
<td>90</td>
<td>232</td>
<td>207</td>
<td>1430</td>
<td>3rd in Northeast</td>
<td align="left">Lost in Conference Semifinals</td>
</tr>
<tr align="center">
<td>2001–02</td>
<td>82</td>
<td>43</td>
<td>25</td>
<td>10</td>
<td>4</td>
<td>100</td>
<td>249</td>
<td>207</td>
<td>1212</td>
<td>2nd in Northeast</td>
<td align="left">Lost in Conference Finals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>2002–03</td>
<td>82</td>
<td>44</td>
<td>28</td>
<td>7</td>
<td>3</td>
<td>98</td>
<td>236</td>
<td>208</td>
<td>1390</td>
<td>2nd in Northeast</td>
<td align="left">Lost in Conference Quarterfinals</td>
</tr>
<tr align="center">
<td>2003–04</td>
<td>82</td>
<td>45</td>
<td>24</td>
<td>10</td>
<td>3</td>
<td>103</td>
<td>242</td>
<td>204</td>
<td>1452</td>
<td>2nd in Northeast</td>
<td align="left">Lost in Conference Semifinals</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>2004–05</td>
<td colspan="11"><i>Season cancelled due to 2004–05 NHL Lockout</td>
</tr>
<tr align="center">
<td>2005–06</td>
<td>82</td>
<td>41</td>
<td>33</td>
<td>--</td>
<td>8</td>
<td>90</td>
<td>257</td>
<td>270</td>
<td>1291</td>
<td>4th in Northeast</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>2006–07</td>
<td>82</td>
<td>40</td>
<td>31</td>
<td>--</td>
<td>11</td>
<td>91</td>
<td>258</td>
<td>269</td>
<td>1065</td>
<td>3rd in Northeast</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center">
<td>2007–08</td>
<td>82</td>
<td>36</td>
<td>35</td>
<td>--</td>
<td>11</td>
<td>83</td>
<td>231</td>
<td>260</td>
<td>1087</td>
<td>5th in Northeast</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>2008–09</td>
<td>82</td>
<td>34</td>
<td>35</td>
<td>--</td>
<td>13</td>
<td>81</td>
<td>250</td>
<td>293</td>
<td>1113</td>
<td>5th in Northeast</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center">
<td>2009–10</td>
<td>82</td>
<td>30</td>
<td>38</td>
<td>--</td>
<td>14</td>
<td>74</td>
<td>214</td>
<td>267</td>
<td>1071</td>
<td>5th in Northeast</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center" bgcolor="#EEEEEE">
<td>2010–11</td>
<td>82</td>
<td>37</td>
<td>34</td>
<td>--</td>
<td>11</td>
<td>85</td>
<td>218</td>
<td>251</td>
<td>985</td>
<td>4th in Northeast</td>
<td align="left">Did not qualify</td>
</tr>
<tr align="center">
<td>2011–12</td>
<td>82</td>
<td>35</td>
<td>37</td>
<td>--</td>
<td>10</td>
<td>80</td>
<td>231</td>
<td>264</td>
<td>824</td>
<td>4th in Northeast</td>
<td align="left">Did not qualify</td>
</tr>
</table>