<style>
#vw-sidemenu-container{ float:left; height: 600px; margin: 0 5px 0 5px; padding: 0 5px 0 0; }
#vw-content-container{ float:left; width: 80%; margin: 0 5px 0 5px; padding: 5px; 
						/*background-image:url(/images/pss/1-69-2.jpg); background-size: 200px 150px; background-repeat:repeat;*/ }
#vw-disqus, #vw-disqus-explanation{ float:left; width: 40%; padding: 20px;}
</style>
<div id="view-content">
	<div id="vw-sidemenu-container">
    </div>
    <div id="vw-content-container">
        <div id="vw-disqus">
        <div id="disqus_thread">
        </div>
		<script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'mysa-pss'; // required: replace example with your forum shortname
    
            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
        </div>
        <div id="vw-disqus-explanation">
            <p>Explanation goes here...</p>
        </div>
     </div>
</div>
<script>
require(["mysa/controllers/Pss", "dojo/dom", "dojo/dom-construct", "dojo/ready",  "dojo/domReady!"],
function(Pss, dom, domConstruct, ready){
	ready(function(){
		var pss = new Pss();
		pss.makeSideMenu();
	});
});
</script>
