<div id="view-content">
</div>
<div id="vw-disqus">
    <div id="disqus_thread">
    </div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'mysa-pss'; // required: replace example with your forum shortname
    
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
<div id="vw-disqus-explanation">
    <p>Explanation goes here...</p>
</div>
<script>
require(["mysa/controllers/Pss", "mysa/views/ViewTemplate",  "dojo/dom", "dojo/dom-construct", "dojo/ready",  "dojo/domReady!"],
function(Pss, ViewTemplate, dom, domConstruct, ready){
	ready(function(){
		var view = new ViewTemplate();
		view.makeSectionMenu(<?php echo $this->jSectionMenuItems; ?>);
		var pss = new Pss();
		domConstruct.place("vw-disqus", "view-content");
		domConstruct.place("vw-disqus-explanation", "view-content");
	});
});
</script>
