<style>
#vw-sidemenu-container{ float:left; height: 600px; margin: 0 5px 0 5px; padding: 0 5px 0 0; }
#vw-content-container{ float:left; width: 85%; margin: 0 5px 0 5px; padding: 5px; 
						/*background-image:url(/images/pss/1-69-2.jpg); background-size: 200px 150px; background-repeat:repeat;*/ }
</style>
<script>
require(["dojo/parser", "dijit/InlineEditBox", "dijit/Editor", "dijit/_editor/plugins/AlwaysShowToolbar"]);
</script>

<div id="view-content">
	<div id="vw-sidemenu-container">
    </div>
    <div id="vw-content-container">
		<script>
        var formVariables = <?php echo $this->formVariables; ?>;
        </script>
        
        <script>
        require(["dojo/parser", "dijit/form/Form", "dijit/form/Button", "dijit/form/ValidationTextBox", "dijit/form/DateTextBox", "dijit/form/ValidationTextBox", "dojox/validate/web"]);
        var pettypes = <?php echo $this->types; ?>;
        var breeds = <?php echo $this->breeds; ?>;
        var initialPetTypeVal = <?php echo $this->initialPetTypeVal; ?>;
        
        require([
             "dojo/ready", "dojo/store/Memory", "dijit/form/Button", "dijit/form/ValidationTextBox", "dijit/form/FilteringSelect", "dojo/dom-attr", "dojo/parser", "dojo/domReady!"
        ], function(ready, Memory, Button, ValidationTextBox, FilteringSelect, domAttr, parser){
            var petStore = new Memory({
                data: pettypes
            });
            var breedStore = new Memory({
                idProperty: "type_id",
                data: breeds
            });
        
            ready(function(){
                var button = new Button({
                    id: "submit",
                    name: "submit",
                    type: "submit",
                    value: "Submit",
                    innerHTML: "Submit"
                }, "submit");
                button = new Button({
                    //id: "name",
                    name: "cancel",
                    type: "cancel",
                    value: "Cancel",
                    innerHTML: "Cancel",
                    onClick: function(){window.location.href = '/pss/pages';}
                }, "cancel");
                var vb1 = new ValidationTextBox({
                    id: "name",
                    name: "name",
                    required: "required",
                    maxlength: 20,
                    regExp:'[a-zA-Z]+',
                    invalidMessage:'Name has invalid characters. A-Z or a-z only'
                }, "name");
                var comboBox1 = new FilteringSelect({
                    id: "pettype",
                    name: "pettype",
                    //value: initialPetTypeVal,
                    store: petStore,
                    searchAttr: "pet_type",
                    required: "required",
                    placeHolder: "Select a type of pet",
                    onChange: function(){result = breedStore.query({type_id:this.value});
                                            mem = new Memory({idProperty: "id", data: result});
                                            dijit.byId('breed').set('store', mem);
                                            dijit.byId('breed').set('searchAttr', "desc");
                                            dijit.byId('breed').set('value', '');}
                }, "pettype");
                var comboBox2 = new FilteringSelect({
                    id: "breed",
                    name: "breed",
                    placeHolder: "Select a breed/subtype",
                    required: "required",
                }, "breed");
            });
        });
        </script>
        <div data-dojo-type="dijit/form/Form" id="myForm" data-dojo-id="myForm" encType="multipart/form-data" action="" method="post" style="margin: 20px 0 0 100px;">  
            <script type="dojo/on" data-dojo-event="submit">
                if(this.validate()){
                    return confirm('All form field inputs look good. Press OK to submit');
                }else{
                    alert('Form contains invalid data.  Please correct invalid data');
                    return false;
                }
                return true;
            </script>
            <table style="border: 1px solid #9f9f9f;" cellspacing="10">
                 <caption style="font-size: 20px; padding: 5px; border: 3px solid green; text-align:left;">
                 <?php echo $this->flags->formCaption; ?></caption>
                <tr>
                    <td>
                        <label class="required" for="name">Name:</label>
                    </td>
                    <td>
                        <input id="name"></input>
                        <p class="desc1">A-Z and a-z only</p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="required" for="pettype">Type of Pet:</label>
                    </td>
                    <td>
                        <input id="pettype"></input>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="required" for="breed">Breed:</label>
                    </td>
                    <td>
                        <input id="breed"></input>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="required">Add a picture:</label>
                    </td>
                    <td>
                        <input type="hidden" name="MAX_FILE_SIZE" value="5000000" id="MAX_FILE_SIZE" />
                        <input type="file" name="file" id="file" required="true"  />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="required" for="mycaptcha">Please fill out ReCaptcha Field:</label>
                    </td>
                    <td>
                        <script type="text/javascript" src="http://www.google.com/recaptcha/api/challenge?k=6LcIPNISAAAAAJAp2oXxFBcVkrvoGeH_lmLhl_4V"></script>
                        <noscript>
                           <iframe src="http://www.google.com/recaptcha/api/noscript?k=6LcIPNISAAAAAJAp2oXxFBcVkrvoGeH_lmLhl_4V"
                               height="300" width="500" frameborder="0"></iframe><br>
                           <textarea id="mycaptcha" name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
                           <input type="hidden" name="recaptcha_response_field" value="manual_challenge">
                        </noscript>
                    </td>
                </tr>
            </table>
            <button id="submit"></button>
            <button id="cancel"></button>
        </div>

    </div>
</div>
<script>
require(["mysa/controllers/Pss", "dojo/dom", "dojo/dom-construct", "dojo/ready",  "dojo/domReady!"],
function(Pss, dom, domConstruct, ready){
	ready(function(){
		var pss = new Pss();
		pss.makeSideMenu();
	});
});
</script>

