<style>
#vw-sidemenu-container{ float:left; height: 600px; margin: 0 5px 0 5px; padding: 0 5px 0 0; }
#vw-content-container{ float:left; width: 85%; margin: 0 5px 0 5px; padding: 5px; 
						/*background-image:url(/images/pss/1-69-2.jpg); background-size: 200px 150px; background-repeat:repeat;*/ }
#vw-page-title{ width: 30%; margin: auto; text-align:center;}
#vw-picture-container{ width:100%; height: 400px; margin: 2px; padding: 5px; border: 1px solid black; overflow: auto;}
#vw-picture{ float:left; width: 500px; margin: 10px 20px 10px 20px; transform:translateY(0px) rotate(0deg); }
#editor{ float:left; width: 600px; margin: 10px 20px 10px 20px; background-color: yellow;}
.vw-title{ padding: 2px 5px 2px 5px; border:1px solid black; background-color:#FFC;}
</style>
<script>
require(["dojo/parser", "dijit/InlineEditBox", "dijit/Editor", "dijit/_editor/plugins/AlwaysShowToolbar"]);
</script>

<div id="view-content">
	<div id="vw-sidemenu-container">
    </div>
    <div id="vw-content-container">
    	<p>This is where you can add new pet pages and manage existing ones. Please select from options to the left to continue.</p>       
    </div>
</div>
<script>
<?php 
if($this->varInits->isPageRequest == true)
{?>
	var pics = <?php echo $this->pics; ?>;
<?php
}
?>
function navigate(uri){
	window.location.href = uri;
}
require([	"mysa/controllers/Pss",
			"dojo/ready", "dijit/Menu", "dijit/MenuItem", "dijit/CheckedMenuItem", "dijit/MenuSeparator", "dijit/PopupMenuItem", "dijit/Editor", "dijit/_editor/plugins/AlwaysShowToolbar",
			"dojo/json", "dojo/dom", "dojo/dom-construct", "dijit/form/Button", "dojo/domReady!"
		],
function(Pss, ready, Menu, MenuItem, CheckedMenuItem, MenuSeparator, PopupMenuItem, Editor, AlwaysShowToolbar, JSON, dom, domConstruct, Button){
    ready(function(){
		var pss = new Pss();
		pss.makeSideMenu();
		var varInits = JSON.parse('<?php echo $this->json; ?>');
		//varInits.isSignedIn = false;
		if(varInits.isSignedIn === true)
		{
			domConstruct.create("h3", {	innerHTML: "Page Menu:" }, "vw-sidemenu-container");
			var pages = JSON.parse('<?php echo $this->pages; ?>');
			var div = domConstruct.create("div", {	id: "vw-sidemenu" }, "vw-sidemenu-container");
			var pMenu;
			pMenu = new Menu({
				//targetNodeIds: ["vw-sidemenu"],//
			}, "vw-sidemenu");
			pMenu.addChild(new MenuItem({
				label: "New Pet Page",
				onClick: "navigate('/pss/newpage')",
			}));
			var pSubMenu = new Menu();
			for (i=0;i<pages.length;i++){
				pSubMenu.addChild(new MenuItem({
					label: pages[i].name + ' [' + pages[i].id + ']',
					onClick: "navigate('/pss/pages/user_id/"+ pages[i].user_id + "/page_id/" + pages[i].id + "')",
				}));
			}
			pMenu.addChild(new PopupMenuItem({
				label: "Your Pet Pages:",
				popup: pSubMenu
			}));
			if(varInits.isPageRequest === true)
			{
				var page = JSON.parse('<?php echo $this->page; ?>');
				pMenu.addChild(new MenuSeparator());
				pSubMenu = new Menu();
				pSubMenu.addChild(new MenuItem({
					label: 'Add a picture',
					onClick: "navigate('/pss/addpicture/user_id/" + page.user_id + "/page_id/" + page.id + "')",
				}));
				pMenu.addChild(new PopupMenuItem({
					label: "Manage this page",
					popup: pSubMenu
				}));
			}
			pMenu.startup();
			//MAKE PAGETITLE
			div = domConstruct.create("div", { id: "vw-page-title" }, "vw-content-container", "first");
			var h1 = domConstruct.create("h1", {	innerHTML: page.name,
													class: "vw-title" }, "vw-page-title");
			div = domConstruct.create("div", { id: "vw-picture" }, "vw-cc-left");
			if(varInits.isPageRequest === true)
			{
				for (i=0;i<pics.length;i++){
				var img = domConstruct.create("img", { 	width: "500",
														src: "/images/pss/" + pics[i].id,
														}, "vw-picture");
				}
				
				var div = new Editor({
								extraPlugins: [AlwaysShowToolbar]
							}, "editor");
				var br = domConstruct.create("br", { clear: "all" }, "vw-content-container");
			}
		}
		else
		{
			var p = domConstruct.create("p", { innerHTML: "Login" }, "vw-content-container");
		}
        
    });
});
</script>
