<?php
if ($this->val == 'fb')
{?>
   <div class="fb-comments" data-href="http://mysocialarea.com" data-width="600" data-num-posts="10"></div>
   <script>
	FB.XFBML.parse();
	</script>
<?php
}
else if($this->val == 'disqus')
{?>
    <div id="disqus_thread" style="width: 70%;"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'mysocialarea'; // required: replace example with your forum shortname
        
            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
<?php }
else{
	?>
    <a class="twitter-timeline"  href="https://twitter.com/search?q=%23mlsesucks"  data-widget-id="308682175929257984">Tweets about "#mlsesucks"</a>
  	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <?php
}
?>
	