<script>
var formVariables = <?php echo $this->formVariables; ?>;
</script>

<script>require(["dojo/parser", "dijit/form/Form", "dijit/form/Button", "dijit/form/ValidationTextBox", "dijit/form/DateTextBox",
					"dijit/form/ValidationTextBox", "dojox/validate/web"]);</script>
<script>
var pettypes = <?php echo $this->types; ?>;

function callback() {
	require(["dojo/request", "dojo/dom"], function(request, dom){
    request("/default/ajax/pssnewpage1").then(
        function(text){
            dom.byId("form-holder").innerHTML = text;
        },
        function(error){
            console.log("An error occurred: " + error);
        }
    );
});
};
require([
     "dojo/ready", "dojo/store/Memory", "dijit/form/Button", "dijit/form/ValidationTextBox", "dijit/form/FilteringSelect", "dojo/dom-attr", "dojo/parser", "dojo/domReady!"
], function(ready, Memory, Button, ValidationTextBox, FilteringSelect, domAttr, parser){
    var stateStore = new Memory({
        data: pettypes
    });

    ready(function(){
		var button = new Button({
            id: "submit",
            name: "submit",
            type: "submit",
            value: "Submit",
			innerHTML: "Submit"
        }, "submit");
		button = new Button({
            //id: "name",
            name: "reset",
            type: "reset",
            value: "Reset",
			innerHTML: "Reset"
        }, "reset");
		button = new Button({
            //id: "name",
            name: "cancel",
            type: "cancel",
            value: "Cancel",
			innerHTML: "Cancel",
			onClick: function(){window.location.href = '/default/pss/pages';}
        }, "cancel");
		var vb1 = new ValidationTextBox({
            id: "name",
            name: "name",
			required: "required",
			maxlength: 20,
			regExp:'[a-zA-Z]+',
			invalidMessage:'Name has invalid characters. A-Z or a-z only'
        }, "name");
        var comboBox1 = new FilteringSelect({
            id: "pettype",
            name: "pettype",
            value: 1,
            store: stateStore,
            searchAttr: "pet_type",
			required: "required",
			onChange: callback
        }, "pettype");
		
        var comboBox2 = new FilteringSelect({
            id: "breed",
            name: "breed",
			required: "required",
           	value: 1,
			//disabled: "disabled",
            store: stateStore,
            searchAttr: "pet_type",
        }, "breed");
		
    });
});
</script>
<div data-dojo-type="dijit/form/Form" id="myForm" data-dojo-id="myForm" encType="multipart/form-data"
		action="" method="post" style="margin: 20px 0 0 100px;">  
    <script type="dojo/on" data-dojo-event="reset">
        return confirm('Press OK to reset widget values');
    </script>
    <script type="dojo/on" data-dojo-event="submit">
        if(this.validate()){
            return confirm('All form field inputs look good. Press OK to submit');
        }else{
            alert('Form contains invalid data.  Please correct first');
            return false;
        }
        return true;
    </script>
    <table style="border: 1px solid #9f9f9f;" cellspacing="10">
    	 <caption style="font-size: 20px; padding: 5px; border: 3px solid green; text-align:left;">
         <?php echo $this->flags->formCaption; ?></caption>
        <tr>
            <td>
                <label class="required" for="name">Name:</label>
            </td>
            <td>
            	<input id="name"></input>
            </td>
        </tr>
        <tr>
            <td>
                <label class="required" for="pettype">Type of Pet:</label>
            </td>
            <td>
            	<input id="pettype"></input>
            </td>
        </tr>
        <tr>
            <td>
                <label class="required" for="breed">Breed:</label>
            </td>
            <td>
            	<input id="breed"></input>
            </td>
        </tr>
        <tr>
            <td>
                <label class="required">Add a picture:</label>
            </td>
            <td>
                <input type="hidden" name="MAX_FILE_SIZE" value="5000000" id="MAX_FILE_SIZE" />
                <input type="file" name="file" id="file" required="true"  />
            </td>
        </tr>
    </table>
    <button id="submit"></button>
    <button id="reset" ></button>
    <button id="cancel"></button>
</div>
