<style>
#vw-page-title{ width: 30%; margin: auto; text-align:center;}
.vw-title{ padding: 2px 5px 2px 5px; border:1px solid black; background-color:#FFC; margin: 10px 0 10px 0;}
#vw-cc-left, #vw-cc-right{ float:left; width: 48%;}
#page-caption{width: 100%, height: 800px; overflow:auto;}
</style>
<div id="vw-page-title">
<h1 class="vw-title"><?php echo $this->page->name; ?> [<?php echo $this->page->id; ?>]</h1>
</div>
<div id="vw-cc-left">
<?php echo $this->partialLoop('ajax/partials/_row-psssearch1-1.phtml', $this->pics); ?>
</div>
<div id="vw-cc-right">
	<h2 class="vw-title">Page Caption:</h2>
    <div id="page-caption">
    <?php echo $this->page->description; ?>
    </div>
</div>
