<div id="view-content">
</div>
<script>
require(["mysa/controllers/Help", "mysa/views/ViewTemplate", "dojo/dom", "dojo/dom-construct", "dojo/ready",  "dojo/domReady!"],
function(Help, ViewTemplate, dom, domConstruct, ready){
	ready(function(){
		var view = new ViewTemplate();
		view.makeSectionMenu(<?php echo $this->jSectionMenuItems; ?>);
		domConstruct.create("p", {
									innerHTML: "Select from the options in the Section Menu for specific help."
								}, "view-content");
	});
});
</script>
