<style>
#div-1{padding:10px; float:left; width: 10%;}
#div-2{padding:10px; float:left; width: 20%; overflow:auto; height: 800px;}
#div-3{padding:20px; float:left; width: 20%;}

</style>

<div id="div-1">
<h2>FILTER:</h2>
<?php echo $this->form; ?>
</div>
<div id="div-2">
<p>ROW COUNT:&nbsp;&nbsp;<?php echo $this->row_count; ?></p>
<?php
if($this->rows_q != NULL) {
?>
<table class='spreadsheet' cellpadding='0' cellspacing='0' width="100%">
    <tr>
        <th>Close Date</th>
        <th>Close Time</th>
    </tr>
    <?php echo $this->partialLoop('qotd/partials/_row-1.phtml', $this->rows_q); ?>
</table>
<?php }else{?>
<p>There are no questions made yet.</p>
<?php }?>
</div>
<div id="div-3">
</div>

<script type="text/javascript">
function getQuestion(val)
{
	var id = val;
	$("#div-3").load( "/admin/ajax/ajax1/val/" + val + "/format/html");
}
</script>
