<div id="view-content">
</div>
<script>
require(["mysa/controllers/User", "mysa/views/ViewTemplate", "dojo/dom", "dojo/dom-construct", "dojo/ready",  "dojo/domReady!"],
function(User, ViewTemplate, dom, domConstruct, ready){
	ready(function(){
		var view = new ViewTemplate();
		//view.makeSectionMenu(<?php //echo $this->jSectionMenuItems; ?>);
		var user = new User(<?php echo $this->identity; ?>);
		//user.makeMenu();
		user.viewOverview();
	});
});
</script>
